### ISSUE TITLE
CRUD Pontos

### ISSUE THREAD

**Issue by guilhermegg8** [BiblioTroca/BiblioTrocaBackEnd#9]
**Point.java** (_Entity_)

Atributos:
- _id_ 
- _walletPoints_

Métodos:
- _construtor vazio_
- _getters_
- _setters_

**PointController.java** 

**PointRepository.java**

**PointService.java**

**PointDTO.java**

--------
**07/09**

Classe _**Point.java**_ iniciada. 

Adição de atributos, getters, setters e construtores.

--------
**08/09**

Import de classe User para classe **Point.java** (Entity). Classe finalizada (v.1).

Classe DTO iniciada e finalizada (v.1).

Classe Repository iniciada e finalizada (v.1).

Classe Controller iniciada.

Classe Service iniciada.

**Comment by leocaje** [comment]
**06/10/23**

Correção das classes Entity, DTO, Controller, Service e Repository.

Inclusão das regras de negócio: métodos _**addPoints()**_ e _**deducePoints()**_.
